{% set name = "lazygit" %}
{% set version = "0.8.2" %}
{% set sha256 = "aaaa4cb789d387a08eb46ca95159561cdb4a2f4e70315ce68ed61bbd30fe24ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jesseduffield/lazygit/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False

requirements:
  build:
    - go

test:
  commands:
    - test -f $PREFIX/bin/lazygit  # [unix]
    - lazygit -h || true  # [unix]
    - if not exist "%LIBRARY_BIN%\\lazygit.exe" exit 1  # [win]
    - lazygit -h || exit 0  # [win]

about:
  home: https://github.com/jesseduffield/lazygit
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: |
    A simple terminal UI for git commands, written in Go with the gocui library.
  doc_url: https://godoc.org/github.com/jesseduffield/lazygit
  dev_url: https://github.com/jesseduffield/lazygit

extra:
  recipe-maintainers:
    - dbast
