{% set name = "lazygit" %}
{% set version = "0.27" %}
{% set sha256 = "56f02ec958fc122da8e7f3eb62abd9a7d7c257f8fcbbe2606fbad0ebfa794f25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jesseduffield/lazygit/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - go

test:
  commands:
    - test -f $PREFIX/bin/lazygit  # [unix]
    - lazygit -h || true  # [unix]
    - if not exist "%LIBRARY_BIN%\\lazygit.exe" exit 1  # [win]
    - lazygit -h || exit 0  # [win]

about:
  home: https://github.com/jesseduffield/lazygit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A simple terminal UI for git commands, written in Go with the gocui library.
  doc_url: https://godoc.org/github.com/jesseduffield/lazygit
  dev_url: https://github.com/jesseduffield/lazygit

extra:
  recipe-maintainers:
    - dbast
