travis:
  secure:
    BINSTAR_TOKEN: gOskrm0409arLnaZBU6/oQx64bRT4OGoFmeuQMp4C/bKdcByjnQUANnahljGYUXXV4jAyDcrdfJMyYGB2KLMLP0r2Qt70qdcrYaoArhmvL+BxMawATpjEBQqAOaEjGqmsMslCqI/ZtKTChnvBOLPwLfdU9feXGqsBw/aJrPdKB2UsDn7nQSAkevG78GzNL1K8kfZpXafoSOIRbgJ5dRm5AstMN6ZCx4Dbu/ZY1TKrywNM24vwic2/LcARaCnU+aEVwr9PL4q14e3Scr8DNy7H+FquLWZ6LQYMe/PbU92nN6P7/8hPGztxRMW2bnz9y/MKCDMe0n3wOBBcM8quXpzbYC+kQM0ULIBp57DajGo6xUYEA2ZP24zEdSrAkKVR42TdTnXZSWdtSNQD4ZRFwUrOy0QS9S0xTJWOywj90bUueC/B2uRPuULv/86ReWB5bXwdTFPaGdqLpMAdBbZ2SZIRS160arHVo7teBbPc5x71A+QP9+/cqTKfDCDmttw9wRSxaf16oxlR2SoBI9Tw3Q2nv/MdikMiVwsZR4+ZtxC6IcbRN+dAReqVcXpoD7uzxI0pf7tSrq6Q87Osutqm4mQ2I8NYUFw4mCoP2HHblU0CTbkZ+/TxcUkhsUXZ4LTROeKgAUjdXTWgqWHajcGQLQnNVdDv/o6i7jfWq7MVhReRU0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
